import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import ClientLayout from "@/components/home/client-layout";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Ecommerce Web",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Cambiar icono de la app */}
        <link rel="icon" href="./logo.jpg" />
      </head>
      <body className={` ${roboto.variable} antialiased`}>
        <ClientLayout>
          <main>{children}</main>
          <Toaster />
        </ClientLayout>
      </body>
    </html>
  );
}
