import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import HeaderLayout from "@/components/home/header-layout";
import FooterLayout from "@/components/home/footer-layout";
import ClientLayout from "@/components/home/client-layout";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Ecommerce Web",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${roboto.variable} antialiased`}>
       <ClientLayout>
          <main>{children}</main>
          <Toaster />
       </ClientLayout>
      </body>
    </html>
  );
}